# Description:
#   A devtools-common options parser.
#   Open-sourced as part of Bazel.
package(default_visibility = ["//visibility:public"])

java_library(
    name = "options",
    srcs = glob(["*.java"]),
    deps = [
        "@com_google_guava_guava//jar",
        "@com_google_code_findbugs_jsr305//jar",
    ],
    exports = [
        "@com_google_guava_guava//jar",
        "@com_google_code_findbugs_jsr305//jar",
    ],
)
